// Hand-pixelled 32 x 32 Teams icon. "." is transparent; each letter indexes a color.
// Rows remain editable as text so artwork changes are visible in code review.
export const palette = Object.freeze({
  a: '#99a6ff',
  b: '#8585fa',
  c: '#7367ee',
  d: '#5546ce',
  e: '#3930a0',
  w: '#ffffff',
})

export const pixels = Object.freeze([
  '................................',
  '...........aaaa.................',
  '.........aaaaaaaa...............',
  '........aaaaaaaaaa..............',
  '.......aaaaaaaaaaaa.............',
  '.......bbbbbbbbbbbb....bbbbb....',
  '.......bbbbbbbbbbbb...bbbbbbb...',
  '........bbbbbbbbbb...bbbbbbbbb..',
  '.........cccccccc....ccccccccc..',
  '...........cccc......ccccccccc..',
  '......................ddddddd...',
  '.......................ddddd....',
  '........aaaaaaaaaa..............',
  '......aaaaaaaaaaaaaa............',
  '.....bbbbbbbbbbbbbbbbcccccccc...',
  '.....bbbbbbbbbbbbbbbbccccccccc..',
  '....bbbbbbbbbbbbbbbbbbddddddddd.',
  '..cccccccccccbbbbbbbbbddddddddd.',
  '.dddddddddddddbbbbbbbbddddddddd.',
  '.dddddddddddddbbbbbbbbddddddddd.',
  '.dddwwwwwwwdddbbbbbbbbddddddddd.',
  '.dddwwwwwwwdddbbbbbbbbddddddddd.',
  '.ddddddwwdddddbbbbbbbbddddddddd.',
  '.ddddddwwdddddbbbbbbbbddddddddd.',
  '.eeeeeewweeeeebbbbbbbbddddddddd.',
  '.eeeeeewweeeeebbbbbbbbddddddddd.',
  '.eeeeeewweeeeebbbbbbbbddddddddd.',
  '.eeeeeeeeeeeeebbbbbbbbddddddddd.',
  '.eeeeeeeeeeeeeccccccccdddddddd..',
  '..eeeeeeeeeeecccccccccdddddddd..',
  '........dddddddddddddddeeeee....',
  '................................',
])
